#!/usr/bin/env ruby

begin
  require 'docker_auto_build/app.rb'
rescue LoadError => e
  require 'rubygems'
  path = File.expand_path '../../lib', __FILE__
  $:.unshift(path) if File.directory?(path) && !$:.include?(path)
  require 'docker_auto_build/app.rb'
end
